couchbase/docs-cb4

content/install/Install.ditamap
content/install/Mac-install.dita
content/install/Ubuntu-install.dita
content/install/Windows-install.dita
content/install/bp-sizingGuidelines.dita
content/install/hostnames.dita
content/install/init-setup.dita
content/install/install-resourceReqs.dita
content/install/rhel-suse-install-intro.dita
content/install/setup-overview.dita
content/install/supported_upgrade-paths.dita
content/install/upgrade-individual-nodes.dita
content/install/upgrade-mac.dita
content/install/upgrade-offline.dita
content/install/upgrade-online.dita
content/install/upgrade-windows.dita
content/install/upgrading.dita
content/install/user-defined-ports.dita
content/monitoring/monitor-warmup.dita
content/ui/ui-settings-autofailover.dita

Install.ditamap has to be fixed to lower case

upper case to correct

---

content/install/bp-sizing-guidelines.dita
content/install/install-client-server.dita
content/install/install-cluster-setup.dita
content/install/install-download.dita
content/install/install-intro.dita
content/install/install-linux.dita
content/install/install-networkPorts.dita
content/install/install-oracle.dita
content/install/install-platforms.dita
content/install/install-production-deployment.dita
content/install/install-resourceReqs.dita
content/install/install-security-bp.dita
content/install/install-security-considerations.dita
content/install/install-swap-space.dita
content/install/install-uninstalling.dita
content/install/install-yum.dita
content/install/install_suse.dita
content/install/installation.ditamap
content/install/macos-install.dita
content/install/pre-install.dita
content/install/rhel-installing.dita
content/install/rhel-multiple-instances.dita
content/install/rhel-non-root-sudo.dita
content/install/rhel-prerequisites.dita
content/install/rhel-suse-install-intro.dita
content/install/ubuntu-debian-install.dita
content/install/ubuntu-non-root-sudo.dita
content/install/win-install.dita

New Installation outline per Anil's new document. Finished Pre-installation and Installation on Linux.

new and edited files for CB4 installation

---

content/admin/cluster-server-setup.dita
content/admin/cluster-setup.dita
content/admin/topic.dita
content/administrator-guide.ditamap
content/concepts/security.dita
content/install/installation.ditamap
content/install/migrate-couchdb.dita
content/install/migrate-mysql.dita

New files checked for links

---

content/cli/cbbackup-tool.dita
content/install/installation.ditamap

Admin map w/o Sizing Guidelines

---

content/sdks/java-2.2/documents-atomic.dita
content/sdks/java-2.2/documents-basics.dita
content/sdks/java-2.2/documents-creating.dita
content/sdks/java-2.2/documents-retrieving.dita
content/sdks/java-2.2/documents-updating.dita
content/sdks/java-2.2/download-links.dita
content/sdks/java-2.2/env-config.dita
content/sdks/java-2.2/getting-started.dita
content/sdks/java-2.2/java-intro.dita
content/sdks/java-2.2/managing-cluster.dita
content/sdks/java-2.2/migrate.dita
content/sdks/java-2.2/overview.dita
content/sdks/java-2.2/querying-n1ql.dita
content/sdks/java-2.2/release-notes.dita

Java 2.2 Rns and updates

---

content/xdcr/xdcr-conflict-resolution.dita
content/xdcr/xdcr-filtering-setup.dita

removed commented-out instances of LWW

minor edits

---

content/sdks/java-2.2/java-dev-guide.ditamap
content/sdks/java-2.2/tutorial3.dita
content/sdks/java-2.2/tutorial4.dita

Needs either @daschl or @ToddGreenstein review.
This is a rather big one so it should probably be built locally and reviewed as HTML...

JCBC-841: rewrite tutorial for CB4 / try-cb-java

---

content/sdks/java-2.2/querying-n1ql.dita

Also made sure that all classes that had been renamed are correctly reflected in the N1QL doc.
See https://issues.couchbase.com/browse/JCBC-835 and https://issues.couchbase.com/browse/JCBC-842

Add Java sections on N1QL optimization and index management

---

content/sdks/c-2.4/release-notes.dita
content/sdks/dotnet-2.1/release-notes.dita
content/sdks/go-beta/release-notes.dita
content/sdks/node-2.0/release-notes.dita
content/sdks/php-2.0/release-notes.dita
content/sdks/python-2.0/release-notes.dita

all release notes have been reformatted

removed nested topics

---

content/sdks/go-beta/atomic-operations.dita
content/sdks/go-beta/bulk-operations.dita
content/sdks/go-beta/documents.dita
content/sdks/go-beta/download-links.dita
content/sdks/go-beta/durability.dita
content/sdks/go-beta/handling-errors.dita
content/sdks/go-beta/handling-timeouts.dita
content/sdks/go-beta/hello-couchbase.dita
content/sdks/go-beta/introduction.dita
content/sdks/go-beta/logging.dita
content/sdks/go-beta/overview.dita
content/sdks/go-beta/performance-tuning.dita
content/sdks/go-beta/release-notes.dita
content/sdks/go-beta/retrieving.dita
content/sdks/go-beta/storing.dita
content/sdks/go-beta/tutorial.dita

One doc bug remains unresolved for GoSDK: DOC-827

DOC-822, 823, 824, 825, 826. Only one missing is DOC-827

---

content/cli/cbcli-intro.dita
content/developer-guide/sdk-overview.dita
content/install/install-production-deployment.dita
content/sdks/c-2.4/overview.dita
content/sdks/dotnet-2.1/getting-started.dita
content/xdcr/xdcr-pause-resume.dita

broken link to sizing guidelines

DOC-844, other edits

---

content/rest-api/rest-endpoints-all.dita
content/sdks/dotnet-2.2/dotnet-intro.dita
content/sdks/dotnet-2.2/release-notes.dita
content/sdks/java-2.1/managing-connections.dita
content/sdks/java-2.2/managing-connections.dita

DOC-487, 766, 836

---

content/sdks/dotnet-2.2/check-and-swap.dita
content/sdks/dotnet-2.2/cluster-helper.dita
content/sdks/dotnet-2.2/dotnet-dev-guide.ditamap
content/sdks/dotnet-2.2/dotnet.xpr
content/sdks/dotnet-2.2/download-links.dita
content/sdks/dotnet-2.2/durability.dita
content/sdks/dotnet-2.2/geo-spatial-views.dita
content/sdks/dotnet-2.2/handling-failover.dita
content/sdks/dotnet-2.2/handling-timeouts.dita
content/sdks/dotnet-2.2/lock-and-unlock.dita
content/sdks/dotnet-2.2/managing-clusters.dita
content/sdks/dotnet-2.2/persistto.dita
content/sdks/dotnet-2.2/prepared-statements.dita
content/sdks/dotnet-2.2/querying.dita
content/sdks/dotnet-2.2/release-notes.dita
content/sdks/dotnet-2.2/replicateto.dita
content/sdks/dotnet-2.2/time-to-live.dita
content/sdks/dotnet-2.2/tutorial-intro.dita
content/sdks/dotnet-2.2/untitled.dita

Mariji -
I decided to download another 30 day trial of oxygen and did the docs directly as dita because of limited time and the difficulty in organizing the translation/merging from markdown to the existing dita.
You will probably want to review, because I am sure I made some mistakes...
Thanks,
Jeff

dotnet 2.2.0 initial docs

---

content/sdks/dotnet-2.2/dotnet-dev-guide.ditamap
content/sdks/dotnet-2.2/dotnet.xpr
content/sdks/dotnet-2.2/download-links.dita
content/sdks/dotnet-2.2/tutorial-intro.dita

Amarantha -
Pull request for final docs ans travel-sample tutorial.
-Jeff

dotnet links updated and tutorial

---

content/sdks/dotnet-2.2/download-links.dita
content/sdks/dotnet-2.2/release-notes.dita

Mariji/Amarantha -
This is a patch fix update to 2.2.0; I published it today.
Please merge are your earliest convenience.
-Jeff

2.2.1 release notes

---

content/sdks/dotnet-2.2/hello-couchbase.dita

pinging @jeffrymorris for sanity check before merge

NCBC-889: Add using directive in helloworld snippet

---

content/sdks/java-2.1/download-links.dita
content/sdks/java-2.1/getting-started.dita
content/sdks/java-2.1/migrate.dita
content/sdks/java-2.1/release-notes.dita
content/sdks/java-2.1/tutorial.dita
content/sdks/java-2.2/download-links.dita
content/sdks/java-2.2/getting-started.dita
content/sdks/java-2.2/migrate.dita
content/sdks/java-2.2/release-notes.dita
content/sdks/java-2.2/tutorial3.dita

2.2.1 and 2.1.5 RNs

---

content/cli/cbbackup-tool.dita
content/cli/cbrestore-tool.dita
content/cli/cbtransfer-tool.dita
content/connectors/elasticsearch-2.1/release-notes.dita
content/connectors/hadoop-1.2/hadoop.dita
content/developer-guide/views-operation.dita
content/developer-guide/views-querying.dita
content/developer-guide/views-writing.dita
content/indexes/mapreduce-view-operation.dita
content/install/rhel-non-root-sudo.dita
content/install/upgrade-xdcr.dita
content/rest-api/rest-user-create.dita
content/rest-api/rest-xdcr-data-encrypt.dita
content/sdks/java-2.1/querying-n1ql.dita
content/sdks/java-2.2/querying-n1ql.dita
content/security/security-admin-access.dita
content/ui/ui-create-databucket.dita
content/ui/ui-managing-views.dita
content/views/views-operation.dita
content/views/views-querying.dita
content/views/views-writing-map.dita
content/views/views-writing-reduce.dita
content/views/views-writing-utility.dita
content/xdcr/xdcr-docs.dita
content/xdcr/xdcr-intro.dita
content/xdcr/xdcr-reg-expressions.dita

Following on from DOC-855, there were a lot of en dashes where there shouldn't have been.

Mass hypen/en dash fix-up.

---

content/rest-api/rest-cluster-autofailover-intro.dita

Count=[0|1] parameter's definition revised

DOC-873, 874

---

content/connectors/spark-1.0/download-links.dita
content/connectors/spark-1.0/getting-started.dita
content/connectors/spark-1.0/java-api.dita
content/connectors/spark-1.0/release-notes.dita
content/connectors/spark-1.0/spark-dev-guide.ditamap
content/connectors/spark-1.0/spark-intro.dita
content/connectors/spark-1.0/spark-sql.dita

@amarantha-k @marijadjovanovic

Update For Spark 1.0.0

---

content/connectors/spark-1.0/download-links.dita
content/connectors/spark-1.0/spark-dev-guide.ditamap
content/connectors/spark-1.0/spark-shell.dita

@marijadjovanovic @amarantha-k

More Spark Fixes

---

content/getting-started/installing.dita

download on Linux

---

content/sdks/java-2.2/querying-n1ql.dita

@daschl this adds examples on how to build CASE, ARRAY and ANY statements using the DSL

Java N1QL documentation on CASE, ARRAY, ANY

---

content/n1ql/n1ql-language-reference/delete.dita
content/n1ql/n1ql-language-reference/insert.dita
content/n1ql/n1ql-language-reference/merge.dita

Reverts couchbase/docs-cb4#133

Revert "Update DML statements for 4.1"

---

content/sdks/python-2.0/release-notes.dita

Reverts couchbase/docs-cb4#135

Revert "python: 2.0.5 release notes"

---

content/sdks/dotnet-2.2/download-links.dita

Marija -
Please merge.
Thanks,
Jeff

Updated download links for 2.2.2

---

content/sdks/java-2.2/documents-basics.dita

Improve documentation on how to deal with BinaryDocument's ByteBuf, when
to release, how to detect and prevent leaks.
Also edited the "Document Basics" table of document types to put internal links to their relevant sections.
@daschl please review this before the PR can be merged in :smile:

JCBC-887 - BinaryDocument buffer mgmt doc

---

content/developer-guide.ditamap
content/developer-guide/memory-errors.dita
content/install/deployment-docker.dita
content/install/install-production-deployment.dita
content/install/upgrading.dita
content/n1ql/n1ql-language-reference/union.dita
content/rest-api/rest-servergroup-post-add.dita
content/sdks/node-2.0/n1ql-queries.dita

DOC-969, 973, 993, 996, 981, 998, 1000, 1001

Bugs DOC-969-1001

---

content/developer-guide/creating-documents.dita
content/developer-guide/durability.dita
content/developer-guide/raw-append-prepend.dita
content/sdks/c-2.4/options.dita

These are applicable to both the 4.0 and master version

misc fixes for C and devguide

---

content/sdks/java-2.2/documents-basics.dita
content/sdks/java-2.2/download-links.dita
content/sdks/java-2.2/getting-started.dita
content/sdks/java-2.2/migrate.dita
content/sdks/java-2.2/release-notes.dita
content/sdks/java-2.2/tutorial3.dita
content/sdks/java-2.2/tutorial4.dita

Java 2.2 updates

---

content/sdks/java-2.2/querying-n1ql.dita

See ticket https://issues.couchbase.com/browse/DOC-1034

Clarification on N1QL Index dsl usage

---

content/sdks/java-2.2/documents-basics.dita
content/sdks/java-2.2/download-links.dita
content/sdks/java-2.2/getting-started.dita
content/sdks/java-2.2/migrate.dita
content/sdks/java-2.2/release-notes.dita
content/sdks/java-2.2/tutorial3.dita

Release notes and changes for Java release 2.2.3

---

content/sdks/java-2.2/documents-atomic.dita
content/sdks/java-2.2/documents-creating.dita
content/sdks/java-2.2/documents-deleting.dita
content/sdks/java-2.2/documents-retrieving.dita
content/sdks/java-2.2/documents-updating.dita

Updates for Java 2.2 from Simon

JCBC-902-docSyncVsAsync

---

content/sdks/dotnet-2.2/download-links.dita
content/sdks/dotnet-2.2/release-notes.dita

added Release Notes and download page changes for .Net 2.2.4

Dotnet 2.2.4

---

content/install/install-production-deployment.dita
content/rest-api/rest-cluster-addnodes.dita

The rest-api file change is probably the most critical to get in ASAP. The page in the 4.0 and 4.1 docs are just flat our wrong at the moment.
Also what are the "Merge remote-tracking branch 'couchbase/master' " things in the commits. They are not changes I made. All I am really trying to update are the files.

Changed 2 files

---

content/sdks/c-2.4/download-install.dita

I am still wondering if this link should be a relative link though since it is linking to an internal document

Fixed incorrect URL

---

content/4.5-dp/enterprise-backup-restore.dita
content/4.5-dp/query-monitoring.dita
content/4.5-dp/whats-new.ditamap

new topics for DP 4.5: Backup&Restore, Query monitoring (placeholders)

Query monitoring, backup&restore for DP 4.5

---

content/sdks/java-2.2/querying-views.dita

- Give example of a SpatialView query with range (JCBC-758)
- Clarify includeDocs target parameter (JCBC-848)
Please wait for review by @daschl before merging.

View usage clarifications

---

content/sdks/java-2.2/overview.dita

Need review from @daschl and @ToddGreenstein.
JCBC-880 is a duplicate of [JCBC-608](https://issues.couchbase.com/browse/JCBC-608) currently affected to Todd and marked as "In Progress".

JCBC-880: Add SDK-server compatibility matrix

---

content/clustersetup/change-settings-bucket.dita
content/concepts/data-management.dita
content/connectors/kafka-1.2/release-notes.dita
content/connectors/spark-1.0/release-notes.dita
content/install/install-ports.dita
content/monitoring/ui-monitoring-statistics.dita
content/n1ql/n1ql-language-reference/insert.dita
content/n1ql/n1ql-language-reference/prepare.dita
content/rest-api/rest-bucket-create.dita
content/sdks/node-2.0/release-notes.dita

Errors in files corrected

---

content/release-notes/release-notes-intro.dita

fixed text in the RN intro file

Release notes for 4.0

---

content/sdks/java-2.2/download-links.dita
content/sdks/java-2.2/getting-started.dita
content/sdks/java-2.2/migrate.dita
content/sdks/java-2.2/release-notes.dita
content/sdks/java-2.2/tutorial3.dita

Java Release Notes and modifications for 2.2.4 release

---

content/cli/cbcli/setting-alert.dita
content/sdks/java-2.2/download-links.dita
content/sdks/java-2.2/env-config.dita
content/sdks/java-2.2/getting-started.dita
content/sdks/java-2.2/migrate.dita
content/sdks/java-2.2/release-notes.dita
content/sdks/java-2.2/tutorial3.dita

Java 2.2.4 and CLI option

---

content/4.5-dp/security-about-x509.dita
content/4.5-dp/security-x509-setup.dita
content/4.5-dp/security-x509.dita

added "security" as the section heading

Security outline changes

---

content/4.5-dp/br-cluster.dita
content/4.5-dp/br-compact.dita
content/4.5-dp/br-create.dita
content/4.5-dp/br-merge.dita
content/4.5-dp/br-remove.dita
content/4.5-dp/br-restore.dita
content/4.5-dp/cb-45.ditamap
content/4.5-dp/enterprise-backup-restore.dita
content/4.5-dp/enterprise-backup.dita
content/4.5-dp/enterprise-restore.dita

added some new files and content for Enterprise B&R

Backup&Restore new files

---

content/4.5-dp/br-howtodo.dita
content/4.5-dp/cb-45.ditamap
content/4.5-dp/enterprise-backup-restore.dita
content/4.5-dp/x509-with-rest.dita

Final review docs for X.509 certificates and Backup & Restore tool

new content for B&R and X509-REST

---

content/4.5-dp/enterprise-backup-restore.dita
content/4.5-dp/installation.dita
content/4.5-dp/relnotes.dita
content/4.5-dp/security-about-x509.dita
content/4.5-dp/security-x509-setup.dita
content/4.5-dp/security-x509.dita

Changes for 4.5-dp release notes: limitations and bugs for array indexes, other edits

limitations, new bugs

---

content/4.5-dp/relnotes.dita

Dons changes from 2/16

---

content/4.5-dp/br-howtodo.dita
content/4.5-dp/whats-new.dita

Sorry, two last minute changes.

Added a little more info about list and changed description

---

content/4.5-dp/security.dita

Intro for the Security section added. DOC-1130

Security intro added

---

content/4.5-dp/enterprise-backup-restore.dita
content/4.5-dp/relnotes.dita

Windows removed from Tools diurectory, added to,Limitations, and MB-18110 added to Known Issues

BR on Windows removed

---

content/sdks/java-2.2/download-links.dita
content/sdks/java-2.2/getting-started.dita
content/sdks/java-2.2/migrate.dita
content/sdks/java-2.2/release-notes.dita
content/sdks/java-2.2/tutorial3.dita

ping @simonbasle (optionally, since he is sick) 
This needs to go in all the stable branches as well - @amarantha-k  can you review and then merge in all branches?
thanks

Java 2.2.5 Release Notes

---

content/backup-restore/br-cluster.dita
content/backup-restore/br-compact.dita
content/backup-restore/br-create.dita
content/backup-restore/br-howtodo.dita
content/backup-restore/br-list.dita
content/backup-restore/br-merge.dita
content/backup-restore/br-remove.dita
content/backup-restore/br-restore.dita
content/backup-restore/enterprise-backup-restore.dita
content/backup-restore/enterprise-backup.dita
content/clustersetup/adding-nodes.dita
content/clustersetup/bucket-setup.dita
content/clustersetup/create-bucket.dita
content/clustersetup/delete-bucket.dita
content/clustersetup/flush-bucket.dita
content/clustersetup/remove-nodes.dita
content/concepts/concepts-rba.dita
content/indexes/querying-using-map-reduce-views.dita
content/security/security-about-x509.dita
content/security/security-x509-setup.dita
content/security/security-x509.dita
content/security/x509-with-cli.dita
content/security/x509-with-rest.dita
content/ui/ui-intro.dita

changes for RBAC, updates from DP merged into 4.5

From DP to 4.5 plus RBAC changes

---

content/install/rhel-non-root-sudo.dita
content/install/ubuntu-non-root-sudo.dita
content/sdks/dotnet-2.2/download-links.dita
content/sdks/dotnet-2.2/release-notes.dita

and non-sudo installation only for dev purposes

.NET 2.2.6

---

content/sdks/java-2.2/env-config.dita

@marijadjovanovic this needs to be applied in both 2.1 and 2.2 versions of the Java SDK documentation. Thanks!

DOCS-1230: clarify ssl configuration properties

---

content/concepts/security.dita
content/connectors/elasticsearch-2.1/adv-usage.dita
content/connectors/elasticsearch-2.1/doc-design-elastic.dita
content/connectors/elasticsearch-2.1/elastic-intro.dita
content/connectors/elasticsearch-2.1/index-query.dita
content/connectors/elasticsearch-2.1/install-intro.dita
content/connectors/elasticsearch-2.1/performance-tuning.dita
content/connectors/elasticsearch-2.1/release-notes.dita
content/connectors/elasticsearch-2.1/trouble-intro.dita
content/connectors/hadoop-1.2/hadoop.dita
content/connectors/intro.dita
content/connectors/kafka-1.2/kafka-getting-started.dita
content/connectors/kafka-1.2/release-notes.dita
content/connectors/spark-1.0/getting-started.dita
content/connectors/spark-1.0/release-notes.dita
content/connectors/spark-1.0/spark-dev-guide.ditamap
content/connectors/spark-1.0/spark-intro.dita
content/connectors/spark-1.0/spark-sql.dita
content/connectors/spark-1.0/spark-streaming.dita
content/connectors/spark-1.0/working-with-rdds.dita
content/connectors/talend/talend.dita
content/security/concepts-rba.dita
content/security/security-data-encryption.dita
content/security/security-iptables.dita
content/security/security-outside-server.dita

and edits for the whole Security section

Connectors reorg, RBAC table

---

content/connectors/kafka-2.0/release-notes.dita

Copy editing

---

content/sdks/java-2.2/documents-basics.dita
content/sdks/java-2.2/download-links.dita
content/sdks/java-2.2/getting-started.dita
content/sdks/java-2.2/migrate.dita
content/sdks/java-2.2/release-notes.dita
content/sdks/java-2.2/tutorial3.dita

@daschl please review before @amarantha-k or @marijadjovanovic can merge it in and propagate as necessary (2.2.6 release of the Java SDK)

Java SDK 2.2.6 Release

---

content/sdks/php-2.0/download-links.dita

@marijadjovanovic @ingenthr @brett19

update download links for php 2.2.0beta2

---

content/developer-guide/sub-doc-api.dita

Edits and updates for Watson Beta.  Note: we will update links as more sdk docs become available.

Updates of subdoc for Watson Beta

---

content/sdks/java-2.1/java-intro.dita
content/sdks/java-2.2/java-intro.dita

/cc @amarantha-k @marijadjovanovic

Fix typo in java example

---

content/travel-app/index.dita

Updated instructions for building travel-sample for CB 4.5

Added support for CB 4.5 for Travel-Sample

---

content/architecture/architecture-intro.dita

@amarantha-k - trying simple changes first on the repo. made simple changes to intro.dita under architecture. pls review to make sure I am not breaking anything :)
-cihan

simple changes to architecture intro page

---

content/sdks/c-2.4/download-install.dita

This newest version has files for jessie and xenial

c: update links for couchbase-release

---

content/sdks/java-2.2/documents-basics.dita
content/sdks/java-2.2/download-links.dita
content/sdks/java-2.2/getting-started.dita
content/sdks/java-2.2/release-notes.dita
content/sdks/java-2.2/tutorial3.dita

@daschl please review before @amarantha-k or @marijadjovanovic can merge it in and propagate as necessary (2.2.7 release of the Java SDK)

Java SDK 2.2.7 Release Notes

---

content/sdk/java/fulltext-sdk-java.dita

Part of the 4.5 doc reorganization effort.

Docs reorg: Java Fulltext chapter

---

content/sdk/java/view-queries-java.dita

Part of the 4.5 docs reorganization effort.

Docs reorg: Java Views chapter

---

content/sdk/java/n1ql-queries-java.dita

Part of the 4.5 docs reorganization effort.

Docs reorg: Java N1QL chapter

---

content/connectors/spark-1.1/download-links.dita
content/connectors/spark-1.1/getting-started.dita
content/connectors/spark-1.1/spark-dev-guide.ditamap
content/connectors/spark-1.1/spark-intro.dita
content/connectors/spark-1.1/spark-shell.dita
content/connectors/spark-1.2/download-links.dita
content/connectors/spark-1.2/getting-started.dita
content/connectors/spark-1.2/java-api.dita
content/connectors/spark-1.2/release-notes.dita
content/connectors/spark-1.2/spark-dev-guide.ditamap
content/connectors/spark-1.2/spark-intro.dita
content/connectors/spark-1.2/spark-shell.dita
content/connectors/spark-1.2/spark-sql.dita
content/connectors/spark-1.2/spark-streaming.dita
content/connectors/spark-1.2/working-with-rdds.dita

Added and verified all 3 versions of Spark

Verify Spark 1.1/1.2 files

---

content/sdks/dotnet-2.2/download-links.dita

Matt -
This should be better. I had an issue with the tool i was using and AWS permissions but it should be resolved now.
https://issues.couchbase.com/browse/DOC-1441
-Jeff

Update API references dotnet

---

content/integration.ditamap
content/reference.ditamap
content/release-notes.ditamap

This adds the "iscollapsed" style.  I verified it'll be on the LI elements in generated output.
@amarantha-k: sending it to you for review and to apply before generating the next ingest file.

Add 'iscollapsed' to style to signal in ingest.

---

content/sdk/java/compatibility-versions-features.dita
content/sdk/java/start-using-sdk.dita

ping @ingenthr @marijadjovanovic @amarantha-k

java 2.3.1

---

content/connectors/spark-1.2/dev-workflow.dita
content/connectors/spark-1.2/download-links.dita
content/connectors/spark-1.2/getting-started.dita
content/connectors/spark-1.2/release-notes.dita
content/connectors/spark-1.2/spark-dev-guide.ditamap
content/connectors/spark-1.2/spark-shell.dita
content/connectors/spark-1.2/spark-streaming.dita

Rebased @daschl's changes on couchbaselabs #653.

spark 1.2.1 docs update

---

content/install/rhel-suse-install-intro.dita
content/sdk/concurrent-mutations-cluster.dita
content/sdk/shared/experimental-pars.dita

changed table description to allow for equal column width and proper display of cell content

DOC-1571, fix CAS table

---

content/sdk/php/start-using-sdk.dita

Amarantha: Please review and merge.  I've added just a bit here after I applied my English filter.

Php windows deployment note

---

content/sdk/php/start-using-sdk.dita

I reviewed the English and spotted a couple of other improvements in flow, which I made.

PHP update install instructions

---

content/security/security-best-practices.dita
content/xdcr/xdcr-managing-security.dita

Fix steps for XDCR security and inks for Best Practices

DOC-1635, DOC-1603

---

content/sdk/dotnet/start-using-sdk.dita

Doc-1652: API Reference link simply states "TODO"

---

content/security/security-comm-encryption.dita

enable and disable CB Console on port 8091

---

content/sdk/php/managing-clusters.dita

Now it in sync with description, which tells it creates 2 map/reduce and
1 spatial views

Fix code snippet.

---

content/developer-guide/sub-doc-api.dita

doMutate and doLookup to execute

DOC-1438 Change to the correct subdoc api

---

content/introduction/editions.dita
content/introduction/intro.dita
content/introduction/whats-new.dita
content/travel-app/index.dita

Should have done a PR a while back.  I can merge locally with latest and resubmit if that's easier.

mostly minor wording, grammar or punct changes

---

content/connector-guides.ditamap
content/connectors/intro.dita
content/connectors/spark-2.0/dev-workflow.dita
content/connectors/spark-2.0/download-links.dita
content/connectors/spark-2.0/getting-started.dita
content/connectors/spark-2.0/java-api.dita
content/connectors/spark-2.0/release-notes.dita
content/connectors/spark-2.0/spark-dev-guide.ditamap
content/connectors/spark-2.0/spark-intro.dita
content/connectors/spark-2.0/spark-shell.dita
content/connectors/spark-2.0/spark-sql.dita
content/connectors/spark-2.0/spark-streaming.dita
content/connectors/spark-2.0/structured-streaming.dita
content/connectors/spark-2.0/working-with-rdds.dita

ping @amarantha-k this is a copy of spark 1.2 and changed/refreshed for spark 2.0 -  please merge and publish soon since we'd like to announce it mid this week at a conference - thank you!
Also please add it to docs.couchbase.com - thanks!

Spark 2.0 docs

---

content/sdk/concurrent-mutations-cluster.dita
content/sdk/java/document-operations.dita
content/sdk/python/document-operations.dita
content/sdk/shared/couchbase-errors.dita

I've finally decided to add a table showing what is and is not possible
with a locked item.

DOC-19: Document GETL behavior better

---

content/analytics/limitations.dita

Added links to the issue list

---

content/analytics/troubleshoot.dita

Updated analytics forum link

---

content/analytics/function-ref.dita

Minor edits to fix heading style

---

content/analytics/quick-start.dita

Added download link

---

content/cli/cbcli/rebalance.dita

@amarantha-k can you please review this as I removed and rewrote some content that wasn't quite appropriate for this page.

DOC-1803: Deprecate adding servers as part of rebalance command

---

content/admin/ui-intro.dita

Updated Couchbase Web Console topic

Formatting updates

---

content/connectors/kafka-3.0/kafka-intro.dita
content/connectors/kafka-3.0/quickstart.dita
content/connectors/kafka-3.0/release-notes.dita

@amarantha-k @1tylermitchell @ingenthr

Graduate Kafka 3.0 to GA

---

content/sdk/java/compatibility-versions-features.dita
content/sdk/java/managing-connections.dita
content/sdk/java/start-using-sdk.dita

ping @amarantha-k @mattcarabine

Update docs for java 2.4.0

---

content/security/security-pam-auth.dita

Assigning this to you @amarantha-k as you wrote the page.
I ran through all of the steps but found they only work on CentOS so I've rewritten them (and removed some unnecessary steps) to work on both Debian-based and RHEL-based platforms.
Also added some syntax highlighting and one or two stylistic changes.

Update PAM setup steps

---

content/sdk/dotnet/client-settings.dita

Describe what the IO Service is and how to configure both Multiplexing and Pooled types.

Add .NET IO Service configuration description

---

content/troubleshooting/troubleshooting-common-errors.dita

Have updated this on this branch only, but needs changing everywhere - @mattcarabine is this where we can use your backport magic?

DOC-2034 - Update FD Limit Recommendation

---

content/sdk/java/start-using-sdk.dita

ping @mattcarabine @amarantha-k I think this also needs 4.6 / 4.5 backporting, thanks!

Bump Java to 2.4.1

---

content/sdk/php/start-using-sdk.dita

1) explicitly mention ZLIB headers
2) increase PCS version, so that it have fix https://github.com/flaupretre/pecl-pcs/issues/6

PHP: Improve steps to install extension from pecl

---

content/sdk/java/start-using-sdk.dita

ping @mattcarabine @couchbase/docs-committers , probably also needs backport :)

Java SDK 2.4.2

---

content/sdk/c.ditamap
content/sdk/dotnet.ditamap
content/sdk/go.ditamap
content/sdk/java.ditamap
content/sdk/nodejs.ditamap
content/sdk/php.ditamap
content/sdk/python.ditamap

Moving Starter Kits from Getting Started to Developer area.

SDK-0002: Added starter kits to SDK ditamaps

---

content/connectors/kafka-3.1/quickstart.dita

this a workaround until https://issues.couchbase.com/browse/DOC-2040 can be addressed

shorten kafka output code blocks

---

content/connectors/spark-1.0/spark-dev-guide.ditamap
content/connectors/spark-2.1/dev-workflow.dita
content/connectors/spark-2.1/download-links.dita
content/connectors/spark-2.1/getting-started.dita
content/connectors/spark-2.1/java-api.dita
content/connectors/spark-2.1/release-notes.dita
content/connectors/spark-2.1/spark-dev-guide.ditamap
content/connectors/spark-2.1/spark-intro.dita
content/connectors/spark-2.1/spark-shell.dita
content/connectors/spark-2.1/spark-sql.dita
content/connectors/spark-2.1/spark-streaming.dita
content/connectors/spark-2.1/structured-streaming.dita
content/connectors/spark-2.1/working-with-rdds.dita

ping @mattcarabine , this needs backporting too I think :)

Add Spark 2.1 docs

---

content/rest-api/rest-views-requests.dita

Copied the warning in from the top level internal settings page.

Add warning that internal settings not supported

---

content/connectors/kafka-3.0/source-configuration-options.dita
content/connectors/kafka-3.1/source-configuration-options.dita

https://issues.couchbase.com/browse/KAFKAC-65

Kafka-Connector: fix parameter name for filter class

---

content/sdk/dotnet.ditamap
content/sdk/php.ditamap
content/sdk/php/sample-app-backend.dita

This gives a short term fix to DOC-2150.  A further update will come in later.

Add PHP sample app backend stub.  To be completed later.

---

content/sdk/php/managing-connections.dita
content/sdk/php/n1ql-queries-with-sdk.dita

@mattcarabine @ingenthr @1tylermitchell

PHP: add notes about cluster-level auth, and cross-bucket N1QL queries

---

content/sdk/php.ditamap

PHP: Update API docs to 2.3.0

---

content/connectors/kafka-3.0/kafka-intro.dita
content/connectors/kafka-3.1/kafka-intro.dita

Fix typos in Kafka connector intro

---

content/introduction/whats-new.dita

Removed 'much simpler' from the Auto Schema Discovery paragraph.

Update to Auto Schema Discovery

---

content/connectors/kafka-3.1/quickstart.dita

Reverts couchbase/docs-cb4#1671

Revert "Update kafka connector versions in quickstart"

---

content/connectors/kafka-3.1/quickstart.dita
content/connectors/kafka-3.1/release-notes.dita

Release notes for Kafka Connector 3.1.3

---

content/sdk/java/start-using-sdk.dita

More 2.4.6 Changes

---

content/sdk/subdocument-operations.dita

Fix grammatical errors

---

content/backup-restore/cbbackupmgr-backup.dita

Fix invalid option on cbbackupmgr

---

content/sdk/dotnet/start-using-sdk.dita

This can be back ported as needed.

Update .NET API docs link to latest release

---

content/cli/cbbackup-tool.dita

Correct mixed up --verbose and --silent descriptions

Correct mixed up descriptions in cbbackup-tool.dita

---

content/getting-started/starter-kits.html

Per discussion with @mattcarabine in hipchat today, I added links to the starter kits.
This PR corresponds to JIRA - https://issues.couchbase.com/browse/DOC-2204
Feel free to review the actual kits as well, you can leave comments here or email/hipchat/JIRA/etc

adding starter kits for backup and restore

---

content/sdk/python/async-programming.dita

Added missing reactor setup and execute steps from Twisted KV example.

Update python twisted async guide

---

content/sdk/dotnet/datastructures.dita
content/sdk/java/datastructures.dita

Brings the descriptions of the bucket-level methods in line with reality.
Adds a section on Collections Framework integration.
@subalakr  @ingenthr Can you please review for accuracy and style?

DOC-1872 Enhance Java data structures guide to emphasize Java Collections Framework implementations

---

content/install/install-ports.dita

Add query and FTS ports to information about configuring user-defined ports

---

README.md

Added information from https://github.com/couchbase/docs-cb4/issues/518

Add clarification on code samples (from Issue#518)

---

content/sdk/java/client-settings.dita
content/sdk/java/compatibility-versions-features.dita
content/sdk/java/start-using-sdk.dita

Bump SDK to 2.5.0

---

content/cli/cbbackup-tool.dita

Examples had [-m ...] and should be -m ...

Correct cbbackup command mode examples

---

content/sdk/sample-application.dita

remove try.couchbase.com mention and make it match 5.0 docs

remove paragraph from travel sample

---

content/analytics/5_ddl.html
content/analytics/9_data_type.html
content/analytics/appendix_2_parameters.html

@cb-docs-robot build analytics

Analytics data types and grammar fixes

---

content/sdk/java/start-using-sdk.dita

Update for 2.5.1

---

content/sdk/c/n1ql-queries-with-sdk.dita

Fix spelling error

---

content/fts/fts-queries.dita
content/fts/full-text-intro.dita

per https://issues.couchbase.com/browse/DOC-2498 and other issues that will be rolled into 5.0 docs.. more commits coming
Do not merge.

FTS 5.0 related updates

---

content/sdk/c.ditamap
content/sdk/dotnet.ditamap
content/sdk/go.ditamap
content/sdk/java.ditamap
content/sdk/nodejs.ditamap
content/sdk/php.ditamap
content/sdk/python.ditamap

just moving down a bit until we revamp overall structure

xattr nav reorg

---

content/sdk/c/full-text-searching-with-sdk.dita
content/sdk/dotnet/full-text-searching-with-sdk.dita
content/sdk/go/full-text-searching-with-sdk.dita
content/sdk/nodejs/full-text-searching-with-sdk.dita
content/sdk/php/full-text-searching-with-sdk.dita
content/sdk/python/full-text-searching-with-sdk.dita

Java didn't have the notice, so no update there

remove fts experimental note from each lang page

---

content/install/install-ports.dita

Added the changes already made to 5.0's page - task-based lists of ports to be opened.

Fixes CBSE-3623

---

content/n1ql/n1ql-language-reference/booleanlogic.dita

Changed the result of (A AND B) from NULL to FALSE (when A = NULL, B = FALSE).

NULL AND FALSE equals FALSE

---

content/install/install-ports.dita

Reworked table & user-defined ports.

DOC-1196 & CBSE-3623.

---

content/install/install-ports.dita

Still verifying XDCR changes but wanted to get this committed.

Massive update to port entries

---

content/install/install-ports.dita

Untangling

---

content/install/install-ports.dita

Internal ports added to table, with footnotes.

CBSE-3623 / DOC-1196

---

content/install/install-ports.dita

As per updates to the 5.0 version of this page - incorporating all of Perry's changes.

DOC-1196 & CBSE-3623

---

content/n1ql/n1ql-language-reference/aggregatefun.dita

Added DISTINCT keyword in Example 11.

DISTINCT keyword missing in Example 11

---

content/release-notes/relnotes.dita

Editing so users aren't confused thinking listed versions are latest versions.

DOC-3104 - tweak wording re: SDK 5.0 version alignment

---

content/cli/cbcli/couchbase-cli-user-manage.dita

128 char username limit / 64 char recommendation

DOC-2461 - the CLI part

---

content/cli/cbcli/couchbase-cli-setting-security.dita

Syntax was wrong it showed setting-password-policy instead of setting-security

Fixing SYNTAX section

---

content/sdk/go/start-using-sdk.dita

Go sdk - remove smart quotes, extra comma from user/pass

---

content/sdk/dotnet/n1ql-queries-with-sdk.dita

Removed duplicate content, and replaced with correct final paragraph on streaming.

Duplicate Content correction

---

content/sdk/java/compatibility-versions-features.dita

minor tidy up

---

content/rest-api/rest-views-intro.dita

(I'm sorry, but this has been bothering since v3.x)

Fixed spelling error for DD PUT REST docs

---

content/sdk/c.ditamap
content/sdk/php.ditamap

Update libcouchbase and php SDK versions

---

content/sdk/dotnet/threshold-logging.dita

Replaced "not useful" code sample with code to override the default values of the tracer

Betwixt DOC-3103 & DOC-3295

---

content/sdk/java/start-using-sdk.dita

Bump for Java 2.5.6

---

content/security/security-certs-auth.dita

5.1 --> 5.5

---

content/indexes/indexing-overview.dita

Tweaked some of the language in the main paragraph too. Let me know if I've violated any style guides :).

DOC-3319: Remove references to FTS being DP

---

content/install/install-ports.dita

Document Analytics ports as requested in MB-27404

MB-27404: update port table with Analytics info

---

content/fts/fts-queries.dita

This is the manual backport of https://github.com/couchbase/docs-cb4/pull/2347

Corrected code snippet formatting per DOC-2722 (4.5)

---

content/sdk/encryption.dita
content/sdk/java.ditamap
content/sdk/java/encrypting-using-sdk.dita

DOC 3229 / DOC-3267

---

content/eventing/eventing-language-constructs.dita

@amarantha-k Looks like after an initial glitch my first pull request has made it to the repo. All thanks to Richard and Siri for their timely help

DOC-3317 Initial updates for feedback

---

content/sdk/java/encrypting-using-sdk.dita

DOC-3408 Update encrypting-using-sdk.dita

---

content/install/init-setup.dita

DOC-3614: Add required param to settings/web example

---

content/sdk/dotnet/full-text-searching-with-sdk.dita

Add .NET search examples based on the Java examples found in:
https://developer.couchbase.com/documentation/server/current/sdk/java/full-text-searching-with-sdk.html

Add .NET FTS examples

---

content/data-modeling/intro-data-modeling.dita

A few cosmetic fixes to the document

A few cosmetic fixes to the document

---

content/sdk/c/sample-app-backend.dita

Used the right article 'a' instead of 'an'.

Fix grammatical error

---

content/sdk/php/sdk-authentication-overview.dita

Part of DOC-3282

---

content/connectors/kafka/quickstart.html
content/connectors/kafka/release-notes.html
content/connectors/kafka/sink-configuration-options.html
content/connectors/kafka/source-configuration-options.html
content/connectors/kafka/streams-sample.html

This PR has a lot of HTML/CSS changes because I've reverted to the default antora theme.
The content changes were already reviewed with PM/eng team through Gerrit.

kafka 3.3.1 docs from asciidoc

---

content/sdk/dotnet.ditamap
content/sdk/dotnet/tracing-from-the-sdk.dita

Based on Java’s version - http://docs-build.sc.couchbase.com/server/5.5/sdk/java/tracing-from-the-sdk.html

.NET RTO example

---

content/sdk/python/threshold-logging.dita
content/sdk/python/tracing-from-the-sdk.dita

Port Tutorial to Python, correct property names

DOC-3725 - RTO Python Docs

---

content/install/upgrade-strategies.dita

Removed some redundancies, cleaned up some bits and added some recommendations
*Can someone please double-check my xref to Delta Recovery as part of the Graceful Failover upgrade option?*

Updated upgrade docs

---

content/sdk/dotnet/sdk-authentication-overview.dita

- update CertAuth examples to new CertAuthenticator instead of manually configuring CertificateFactory
- fix up some whitespace (VS Code auto removes it)

Update dotnet CertAuth examples

---

content/connectors/spark-2.2/getting-started.dita

Also updates the existing example for Couchbase Server 5.X+

SPARKC-87 - document how to use connector with spark-submit

---

content/cli/cbbackup-tool.dita

DOC-1060: cbbackup needs to own its entire archive

---

content/sdk/python/sdk-authentication-overview.dita

DOC-3282,PYCBC-510: Cert Auth examples need refining.

---

content/sdk/c.ditamap

For DOC-3727

---

content/cli/cbbackup-tool.dita
content/cli/cbbackup-wrapper.dita
content/cli/cbrestore-tool.dita

DOC-1927: Clarify Compress and Uncompress Options

---

content/getting-started/do-a-quick-install.dita

Reverts couchbase/docs-cb4#2638

Revert "DOC-3782 Add new sandbox container link to 5.0 "Start Here" documentation"

---

content/sdk/python/start-using-sdk.dita

DOC-1994: Python SDK installation on Windows

---

content/cli/cbstats/cbstats-key.dita
content/cli/cbstats/cbstats-vkey.dita

Updated cbstats-key and cbstats-vkey:
* Request syntax formatting
* Updated key information
* Add note and example on cbc-hash
* Update response examples

DOC-1885: providing the vbucket id

---

content/backup-restore/enterprise-backup-restore.dita

Added "Version Compatibility" section explaining:
* cbbackupmgr / host version compatibility
* restore data version compatibility

DOC-3347: clarify support matrix of cbbackupmgr

---

content/cli/cbstats/cbstats-timing.dita

Added note on useful stats. Also:
* Added undocumented stats
* Brought synopsis in line with other cmds
* Updated output

DOC-2174: add useful stats on cbstats:timings

---

content/eventing/eventing-api.dita

DOC-3938:Port details updated for Eventing from 8091 to 8096

---

content/install/installation.ditamap
content/install/running-couchbase-in-containers.dita

This is the update that contains the Operator GA changes to the Dev Portal. I removed Operator from the DITA map and also made new links to in the container documentation.

Removed Operator from ditamap; updated in container docs
