- content/developer-guide/expiry.dita
Link was a placeholder not following Java naming convention.
> fix link to Expiration example in Java

- content/sdks/java-2.2/managing-views.dita
Added a sections in Java SDK 2.2 "View Management" topic about adding/replacing a single view in an existing design document.
see http://issues.couchbase.com/browse/JCBC-852
> JCBC-852: document replacing a view through SDK

- content/views/spatial-views.dita
This change makes the first example a bit simpler/clearer.
> Improve the code of the first example

- content/developer-guide/query-workbench-intro.dita
These URLs replaced the link to the Factory, which was disabled for security reasons.
> added a table with URLs for downloading the packages for Mac, Windows, and Linux

- content/sdks/java-2.1/download-links.dita
- content/sdks/java-2.1/getting-started.dita
- content/sdks/java-2.1/migrate.dita
- content/sdks/java-2.1/release-notes.dita
- content/sdks/java-2.1/tutorial.dita
- content/sdks/java-2.2/release-notes.dita
This change is for 2.1.6 release, so mainly impacting java2.1 folder.
There was a typo in java2.2 latest release note.
Pinging @daschl for quick review.
This will have to be backported as needed, @amarantha-k and @marijadjovanovic
> Release Notes for Java SDK 2.1.6

- content/sdks/java-2.2/documents-atomic.dita
- content/sdks/java-2.2/documents-creating.dita
- content/sdks/java-2.2/documents-deleting.dita
- content/sdks/java-2.2/documents-retrieving.dita
- content/sdks/java-2.2/documents-updating.dita
Mainly async code used in place of sync code (or missing bucket.async()).
This also covers DOC-1007 and JCBC-845.
@daschl can you review before this can be merged in?
> JCBC-902: fix outdated snippets in documents topics

- content/cli/cbcli/setting-alert.dita
- content/sdks/java-2.2/download-links.dita
- content/sdks/java-2.2/getting-started.dita
- content/sdks/java-2.2/migrate.dita
- content/sdks/java-2.2/release-notes.dita
- content/sdks/java-2.2/tutorial3.dita
All changes for Java 2.2.4, including the file tutorial3.dita, which is not part of this ditamap.
Added option for CLI setting-alert
> Changes for Java 2.2.4

- content/cli/cbcli/bucket-create.dita
- content/install/rhel-multiple-instances.dita
- content/install/rhel-non-root-sudo.dita
- content/install/ubuntu-non-root-sudo.dita
- content/xdcr/xdcr-create.dita
- content/xdcr/xdcr-flush.dita
The one to bucket-create.dita is just a flat out wrong thing in the docs and needs to be fixed ASAP.
These changes needs to be backported to all 4.x branches.
> 4 minor changes

- content/sdks/c-2.4/download-install.dita
This is confusing for most homebrew users, and is a standard homebrew
option rather than couchbase-specifici
> C: Remove lipo reference

- content/sdks/php-2.0/download-links.dita
@amarantha-k I've updated links for beta3, but unfortunately I do not have access to docs s3 bucket, could you extract this archive there?
[couchbase-php-client-2.2.0beta3.tar.gz](https://github.com/couchbase/docs-cb4/files/282267/couchbase-php-client-2.2.0beta3.tar.gz)
> download links for php 2.2.0beta3

- content/install/install-platforms.dita
MAC 10.8 should be put into deprecated list and removed from supported platform list.
> Update Supported Platforms for 4.5

- content/sdks/java-2.2/documents-basics.dita
- content/sdks/java-2.2/download-links.dita
- content/sdks/java-2.2/getting-started.dita
- content/sdks/java-2.2/migrate.dita
- content/sdks/java-2.2/release-notes.dita
- content/sdks/java-2.2/tutorial3.dita
The download-links doesn't list a CURRENT since it'll be supersed by 2.3.0
in a matter of days.
Added an item that was forgotten in 2.2.7's release notes.
pinging @ingenthron or @daschl for review :bow:
> Release notes for Java 2.2.8 and fixed 2.2.7

- content/sdk/c.ditamap
- content/sdk/nonjson.dita
- content/sdk/shared/couchbase-errors.dita
Also fixed another instance where it seems we've embedded an http://
link which could've been replaced by a direct DITA reference.
> DOC-1618: Fix broken link to CAS

- content/sdk/nodejs/start-using-sdk.dita
@amarantha-k this was failing as the file it was referring to does not exist in the repo.
As far as I can tell this file is completely external so I've changed it to a html link to the page instead. Please let me know if there is a better way to achieve this that isn't so 'hard-coded'.
> DOC-1782: Update release notes URL

- content/sdk/core-operations.dita
For some reason we used a 'hazardstatement' on this page, this renders to a 'Remember' note on our main site so I just changed the element the information was stored in. This was so that I could add a third note to this section.
Will need to be backported to 4.5 when approved.
> DOC-1406: Clarify how ttl handles time

- content/rest-api/rbac.dita
Removes empty code block from RBAC delete user example
> Remove empty codeblock from delete example section

- content/connectors/kafka-3.1/release-notes.dita
Also according to KAFKAC-63 duplicate 3.0.x release notes here
/cc @mattcarabine
> Update release notes for Kafka Connector 3.1.2

- content/sdk/dotnet/releases.dita
Adds links for 2.4.0 and 2.4.2, plus some formatting updates.
Also probably worth back-porting to previous versions as it's just reference for client versions.
> Update dotnet releases for 2.4.2

- content/n1ql/n1ql-rest-api/exauthrequest.dita
Object closing parenthesis must be after double quote instead of before, otherwise this is an invalid JSON object.
> Fix typo in example

- content/tools/cbexport.dita
```
cbexport json -c couchbase://127.0.0.1 -u Administrator -p password \
-b default -0 /data/lines.json -f lines -t 4
```
should be 
```
cbexport json -c couchbase://127.0.0.1 -u Administrator -p password \
-b default -o /data/lines.json -f lines -t 4
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/docs-cb4/1365)
> update for example with correct flag

- content/sdk/go/document-operations.dita
Solves ‘type interface {} is not an expression’ for Go SDK.
> Solves type interface in Go SDK

- content/sdk/c/start-using-sdk.dita
This confused a user into thinking we no longer supported libev.
> Mention libev more

- content/connectors/spark-1.0/spark-shell.dita
- content/connectors/spark-2.0/spark-intro.dita
- content/connectors/spark-2.0/spark-shell.dita
This is very popular search result page for our docs, possibly due to general search for "spark shell".  
Adding a Note to the page to point to updated connector version should help guide people to newer content.
> Add note to redirect user to new version of spark docs

- content/sdk/dotnet/collecting-information-and-logging.dita
NLog updated the way ASP.NET 5 and .NET Core applications work which made our example not applicable.
This commit updates the example to use the new NLog setup.
This can be back-ported to previous versions.
> Update dotnet core logging with NLog example

- content/sdk/python/start-using-sdk.dita
Fixes typo in Python's getting started guide when using a named variable in N1QL query.
> Add $ prefix to named variable in statement text

- content/sdk/java/managing-connections.dita
Show how to create a cluster from a connection string using the Java SDK, and document the limitations of this technique.
> DOC-1733 Java SDK does not cover connection string in connection info

- content/install/install-swap-space.dita
Fixed 2 typos in install-swap-space.dita for DOC-2683
2x "swappines" -> "swappiness"
> DOC-2683: fixed 2 typos in install-swap-space.dita

- content/connectors/spark-2.2/spark-intro.dita
We recently added a new section for Spark Connector 2.2, but forgot to update the title to reflect the new version.
(followup to d04e815ccf7385f0fd388562d6c110a040ef7b13)
> Fix Spark version

- content/n1ql/n1ql-rest-api/exauthhttp.dita
Obviously the normal user doesn't type directly the authorization header, but instead he uses the curl "user (-u)" option instead.
> Unclear n1ql rest API usage

- content/sdk/c/document-operations.dita
TTL was incorrectly described as "one year, in seconds" when the value is in fact one month in seconds
> Update C SDK documentation for document operations

- content/connectors/kafka-3.1/quickstart.dita
- content/connectors/kafka-3.1/sink-configuration-options.dita
- content/connectors/kafka-3.1/source-configuration-options.dita
Document the 'connection.username' and 'connection.password' config
properties.
Plus a little bit of cleanup.
> DOC-2642: Update Kafka Connector Quickstart with info about RBAC auth

- content/security/security-saslauthd-new.dita
Quick fix for DOC-2574:
"Version required of 'cyrus-sasl' for CentOS 6 is incorrect"
added CentOS 7, and changed CentOS 6's saslauthd version.
> Ready to merge: Update security-saslauthd-new.dita

- content/release-notes/relnotes.dita
It appears that the "Important" not should be a point on it's own, however this renders strangely 
Copying the format of the "Remember" note below should fix this.
> Remove errant bullet point

- content/sdk/interface-stability-pars.dita
- content/sdk/python/compatibility-versions-features.dita
Add a Python platform/SDK support matrix and OS support info.
Python 3.2 will not be supported for SDK 2.3.0 due to
deprecation by nosetest, PIP/setuptools teams, and is
generally considered EOL.
> PYCBC-403: Define supported Python platforms.

- content/sdk/java/async-programming.dita
After bucket.get ("id") operation, timeout is only possible with asynchronous use.
> The incorrect sample was corrected

- content/tools/cbexport.dita
The code block for the job export calls cbimport instead of cbecport.
> Incorrect reference to cbimport

- content/getting-started/index.dita
- content/install/docker-deploy-multi-node-cluster.dita
- content/install/docker-deploy-single-node-cluster.dita
- content/install/getting-started-docker.dita
- content/n1ql/n1ql-language-reference/insert.dita
- content/n1ql/n1ql-language-reference/selectintro.dita
I think I caught them all: docs were previously moved or consolidated from travel-app -> sdk/sample-application .  
@tonyjhillman do you think that covers off the changes you made earlier?
> Redirect old links to sdk sample-application

- content/analytics/2_expr.html
- content/analytics/3_query.html
- content/analytics/6_n1ql.html
- content/analytics/diff-lang.dita
- content/analytics/primer-beer.html
- content/introduction/whats-new.dita
- content/n1ql/n1ql-language-reference/comparisonops.dita.bak
- content/n1ql/n1ql-language-reference/select-syntax.dita
- content/release-notes/relnotes.dita
This has come up previously - Smart Quotes are bad. They make code blocks invalid, making the end user experience terrible.
This commit is slightly overzealous - it replaces every one, not just those in code blocks. I think this is better though, and perhaps it would be good to add an anti-Smart-Quote commit validation at some point.
> [4.5] Replace all occurrences of Smart Quotes (“”)

- content/connectors/kafka-3.2/quickstart.dita
- content/connectors/kafka-3.2/release-notes.dita
- content/connectors/kafka-3.2/sink-configuration-options.dita
- content/connectors/kafka-3.2/source-configuration-options.dita
Kafka Connector 3.2.2 release notes and documentation for new config options.
> Update Kafka Connector docs for version 3.2.2

- content/install/install-ports.dita
These ports aren't required for XDCR, as XDCR has no knowledge of the Query Service (e.g. replicating to a cluster with no Query Service at all). @RichardSmedley has further changes in the works, but it would be good to get this quickly fixed now :)
> Fix 4.6 Query Ports for XDCR

- content/rest-api/rest-fts-indexing.dita
type `bleve` returns `unknown indexType: bleve`. The admin interface uses `fulltext-index`
> Fix incorrect index type

- content/security/security-ldap-tbls-new.dita
doc shows: "dial unix /var/run.sasl2/mux: no such file or directory"
instead of: "dial unix /var/run/sasl2/mux: no such file or directory"
> Fixing Typo: missing /

- content/architecture/connectivity-architecture.dita
There are four main types of access points -> There are five main types of access points
(it's confusing that words "there are four main types" are followed by 5-row table)
> Fix a typo

- content/security/security-authorization.dita
This update explicitly lists the 3 roles available in community edition, as well as the tokens you need if you are using couchbase-cli to create users.
> Explicitly listing the roles in Community Edition

- content/sdk/java/sdk-authentication-overview.dita
For the older client SDK versions which do not have inbuilt support for RBAC, connecting to Couchbase Server 5.
> DOC-3087 pre-RBAC SDK

- content/backup-restore/cbbackupmgr-archivelayout.dita
Fixed "archive backup" -> "backup archive"
Rest of text ideally needs revising to be clearer, such as the statement "The top level directory of the archive is called the backup archive" but this fixes word reversal issue.
> Updated cbbackupmgr-archivelayout.dita

- content/connectors/kafka-3.2/quickstart.dita
- content/connectors/kafka-3.2/release-notes.dita
- content/connectors/kafka-3.2/sink-configuration-options.dita
- content/connectors/kafka-3.2/source-configuration-options.dita
* Release notes for Kafka connector 3.2.3.
* Documentation updates for new config keys.
* Correct a mistake in the quickstart guide. The user needs "Data DCP Reader",
not general read access.
> Update Kafka Connector docs for version 3.2.3

- content/cli/cbcli/couchbase-cli-cluster-init.dita
Hi,
CB_REST_PASSWORD is documented twice, i've removed the less complete one
Thanks,
> remove duplicate on couchbase-cli cluster-init

- content/fts/fts-queries.dita
I've ported the code snippet formatting
**from**: https://developer.couchbase.com/documentation/server/5.1/fts/fts-response-object-schema.html
**to**: https://developer.couchbase.com/documentation/server/4.6/fts/fts-queries.html
I suppose I should have asked if 4.6 is the actual branch that we last published to the website, and not something like 4.6_modified.
> Corrected code snippet formatting per DOC-2722 (4.6)

- content/clustersetup/ui-logs.dita
> doc: fix: warning is not a valid logging level

- content/rest-api/rest-bucket-create.dita
It may not be clear that the Request Data should be in the body of the POST as a form parameter. Someone passing the values in the URL or as JSON will get a possibly confusing response.
Since this is common in most of the endpoint documentation, do you think it would be a good idea to create a new documentation page under the REST area to explain the details of making a HTTP POST/PUT/GET etc and just link to that instead of having to put these details on every REST doc page?
> Add more specifics around the Request Data expected

- content/security/concepts-rba-for-apps.dita
The full bucket access role name should be 'bucket_full_access' not 'bucket_sasl'.
If the current value of 'bucket_sasl' is used, a 400 (Bad Request) response is returned from the server. I've tested this on 5.0, 5.1 and 5.5-beta.
NOTE: I originally used 'bucket_admin' but this is not available in CE edition where 'bucket_full_access' is.
> Update full access bucket role to 'bucket_full_access'

- content/sdk/go/sdk-xattr-example.dita
`gocb.PasswordAuthenticator{
Username: "Administrator",main.go
Password: "password",
}
`
to
`gocb.PasswordAuthenticator{
Username: "Administrator",
Password: "password",
}
`
> Fixing misspelling in sdk-xattr-example 

- content/sdk/dotnet/threshold-logging.dita
- content/sdk/shared/tracing.dita
- update threshold logging configuration names / defaults
- add orphan / zombie response logging configuration properties (maybe these need to be separate?)
- update .NET code example to update Threshold tracer default values
Also looks like my VS Code editor picked up some whitespace and removed it too.
> Vulcan RTO updates

- content/sdk/development-intro.dita
Some missing options in the sample `cbc` command caused the command does not work.
> fix missing command line options in documentation

- content/cli/cbcli/couchbase-cli-user-manage.dita
Looks like it's just data_writer, but otherwise correct.
> Documentation correction on data_reader_writer role

- content/sdk/dotnet/start-using-sdk.dita
This will need back porting to older documentation versions too
> Update .NET API ref link to 2.6.0 release

- content/cli/cbcollect-info-tool.dita
* Add descriptions of new logs.
* Add new example output.
* Minor markup and punctuation changes.
> DOC-3257: update cbcollect_info arguments and examples

- content/cli/cbstats/cbstats-allocator.dita
Update example with jemalloc output.
Bring synopsis in line with other cbstats help.
> DOC-2488: cbstats allocator wrong

- content/eventing/eventing-api.dita
Corrects the port for the eventing REST API (it's not at port 8091 but at 8096).
> Point out the port for the eventing REST API.

- content/cli/cbstats/cbstats-uuid.dita
- content/cli/cbstats/cbstats-workload.dita
- content/release-notes/relnotes-v5.0.x.dita
- content/security/concepts-rba.dita
* use correct number of columns in cols attribute on table
* fix xref targets
> patch syntax errors in DITA sources (5.1)

- content/cli/cbstats/cbstats-uuid.dita
- content/cli/cbstats/cbstats-workload.dita
- content/install/install-production-deployment.dita
* use correct number of columns in cols attribute on table
* replace nested concept elements with section elements
> patch syntax errors in DITA sources (5.5)
